name: flet_android_background
description: Foreground task lifecycle for Flet Android apps
version: 0.0.2
publish_to: none
environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.4'
dependencies:
  flutter:
    sdk: flutter
  flet: '>=0.82.0 <2.0.0'
flutter:
  plugin:
    platforms:
      android:
        package: dev.alexstoica.background
        pluginClass: BackgroundPlugin
